name: CI

on:
  push:
    branches:
      - main
    paths:
      - Project/backend/**
  pull_request:
    branches:
      - develop
    paths:
      - Project/backend/**

defaults:
  run:
    working-directory: main/Project/backend/

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          path: main

      # Install python
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip install -r codebase/requirements.txt
          pip install black

      - name: Run linting
        run: |
          black --check . || echo "::warning::Code formatting issues found. Please run black to format your code."

      - name: Run tests
        run: bash scripts/test.sh
